### ISSUE TITLE
How to  judge the correct of the generated char_freq.cp file if Ｉuse your code to do Arabic frequency count?

### ISSUE THREAD

**Issue by yingning** [tongpi/synthtext100kCH#5]
Dear friend .Thanks for your share code. How to  judge the correct of the generated char_freq.cp file if Ｉuse your code to do Arabic frequency count? @doudoubean @gitter-badger @zj463261929 @wulivicte @ten2net

**Comment by doudoubean** [comment]
I think princle is the same. but my code  is designed for Chinese。You should  take into consideration that Arabic has its characteristic itself. The char_freq.cp file is serialized by cPickle，if you want to validate the correct of the generated char_freq.cp file, you can Deserialize it.
