### ISSUE TITLE
数据集地址

### ISSUE THREAD

**Issue by wushilian** [tongpi/synthtext100kCH#6]
请问能提供数据集下载地址吗

**Comment by doudoubean** [comment]
你好，数据集是我们参考[SynthText](https://github.com/ankush-me/SynthText)项目合成的，而且比较大。因为合成结果都属于公司产出物，所以不便分享。希望见谅！

**Comment by doudoubean** [comment]
当然，如果你确实需要数据集，可以参考清华大学这个项目的公开部分数据集https://ctwdataset.github.io/

**Comment by wushilian** [comment]
@doudoubean 好的，谢谢
